name: flutter_neo_bank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0

  # Routing
  go_router: ^16.3.0

  # Utilities
  intl: ^0.20.2
  faker: ^2.1.0
  csv: ^6.0.0
  path_provider: ^2.1.4

  # Charts
  fl_chart: ^1.1.1

  # PDF & Printing
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/neobank01.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"  # White background
  image: assets/neobank01.png  # Your logo (already has red color)
  android: true
  ios: true
  
  # For Android 12 and above
  android_12:
    color: "#FFFFFF"  # White background
    image: assets/neobank01.png
    icon_background_color: "#FFFFFF"  # White background

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/neobank01.png
    - assets/neobank02.png