name: flutter_neo_bank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  go_router: ^16.3.0
  intl: ^0.20.2
  fl_chart: ^1.1.1
  pdf: ^3.11.1
  printing: ^5.13.2
  csv: ^6.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/neobank01.png"  # Changed to neobank01.png
  adaptive_icon_background: "#FFFFFF"  # Optional: set background color
  adaptive_icon_foreground: "assets/neobank01.png"  # Optional: for Android adaptive icons

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/neobank01.png
    - assets/neobank02.png