name: flutter_neo_bank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  go_router: ^16.3.0
  intl: ^0.20.2
  fl_chart: ^1.1.1
  pdf: ^3.11.1
  printing: ^5.13.2
  csv: ^6.0.0              # Add this line
  path_provider: ^2.1.4     # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/neobank02.png